### ISSUE TITLE
<> -> False    translates to  =

### ISSUE THREAD

**Issue by massimotisi** [atlanmod/CoqTL#34]

**Comment by veriatl** [comment]
Theorem tr_applyRuleOnPattern_None : 
   forall eng: TransformationEngine,
      forall (tr: Transformation) (sm : SourceModel) (r: Rule) (sp: list SourceModelElement),
        length sp <> length (getInTypes r) ->
        applyRuleOnPattern r tr sm sp <>  None -> False.

===>

Theorem tr_applyRuleOnPattern_None : 
   forall eng: TransformationEngine,
      forall (tr: Transformation) (sm : SourceModel) (r: Rule) (sp: list SourceModelElement),
        length sp <> length (getInTypes r) ->
        applyRuleOnPattern r tr sm sp = None.

**Comment by veriatl** [comment]
addressed by #57
