### ISSUE TITLE
Remove the nil case from tr_instantiatePattern_None_tr

### ISSUE THREAD

**Issue by massimotisi** [atlanmod/CoqTL#53]
"Theorem tr_instantiatePattern_None_tr : 
  forall t: TransformationEngine,
    forall (tr: Transformation) (sm : SourceModel) (sp: list SourceModelElement),
      getRules tr = nil ->
      (instantiatePattern tr sm sp = None \/
       instantiatePattern tr sm sp = Some nil)."

**Comment by massimotisi** [comment]
and
"Theorem tr_applyPattern_None_tr : 
  forall t: TransformationEngine,
    forall (tr: Transformation) (sm : SourceModel) (sp: list SourceModelElement),
        getRules tr = nil ->
        (applyPattern tr sm sp = None \/
         applyPattern tr sm sp = Some nil)."

**Comment by veriatl** [comment]
addressed by #56
